# CREFC IRP v8.4 header definitions (extracted from validated CoreVest 2018-1 converted files)
CREFC_HEADERS = {
 "CBND": [
  "Transaction ID",
  "Distribution Date",
  "Record Date             ",
  "Class Name/Class ID",
  "Cusip",
  "Original Note Amount   (fka Original Balance)",
  "Notional Flag",
  "Bond Beginning Balance",
  "Scheduled Principal Amount   (fka Scheduled Principal)",
  "Unscheduled Principal Collections   (fka Unscheduled Principal)",
  "Total Principal Distribution",
  "Negative Amortization/Deferred Interest Capitalized Amount   (fka Neg Am/Deferred Interest Amount)",
  "Realized Loss (Gain) to Trust   (fka Realized Loss (Gain))",
  "Cumulative Unreimbursed Realized Loss to Trust",
  "Bond Ending Balance",
  "Current Index Rate",
  "Remittance Rate/Pass Through Rate",
  "Interest Accrual Method   (fka Accrual Method)",
  "Accrual Days",
  "Accrued Interest   (fka Interest Accrued)",
  "Prepayment Penalty/Premium Allocation",
  "Yield Maintenance Allocation",
  "Other Interest Distribution",
  "Prepayment Interest Excess (Shortfall)   (fka Prepayment Interest Shortfall)",
  "Not Used",
  "Interest Shortfall/(Excess)",
  "Total Interest Distribution",
  "Not Used",
  "Cumulative Prepayment Penalty/Premium Allocation",
  "Cumulative Yield Maintenance Allocation",
  "Beginning Unpaid Interest Balance",
  "Ending Unpaid Interest Balance",
  "Rating Agency 1 - Original Rating",
  "Rating Agency 1 - Most Recent Rating",
  "Rating Agency 1 - Date Transmitted from Rating Agency",
  "Rating Agency 2 - Original Rating",
  "Rating Agency 2 - Most Recent Rating",
  "Rating Agency 2 - Date Transmitted from Rating Agency",
  "Rating Agency 3 - Original Rating",
  "Rating Agency 3 - Most Recent Rating",
  "Rating Agency 3 - Date Transmitted from Rating Agency",
  "Rating Agency 4 - Original Rating",
  "Rating Agency 4 - Most Recent Rating",
  "Rating Agency 4 - Date Transmitted from Rating Agency",
  "Rating Agency 1 Code",
  "Rating Agency 2 Code",
  "Rating Agency 3 Code",
  "Rating Agency 4 Code",
  "Trustee",
  "Certificate Administrator",
  "Current Subordinate Percentage"
 ],
 "CCOL": [
  "Transaction ID",
  "Group ID",
  "Distribution Date",
  "Original Loan Count",
  "Ending current period loan count",
  "Current Ending Scheduled Balance   (fka Ending current period collateral balance)",
  "1 month Delinquent - number",
  "1 Month Delinquent - Ending Scheduled Balance   (fka 1 month Delinquent - scheduled balance)",
  "2 months Delinquent - number",
  "2 Months Delinquent - Ending Scheduled Balance   (fka 2 months Delinquent - scheduled balance)",
  "3 months Delinquent - number",
  "3 Months Delinquent - Ending Scheduled Balance   (fka 3 months Delinquent - scheduled balance)",
  "Foreclosure - number",
  "Foreclosure - Ending Scheduled Balance   (fka Foreclosure - scheduled balance)",
  "REO - number",
  "REO - Ending Scheduled Balance   (fka REO - scheduled balance)",
  "Specially serviced - number",
  "Specially Serviced - Ending Scheduled Balance    (fka Specially serviced - scheduled balance)",
  "In Bankruptcy - number",
  "In Bankruptcy - Ending Scheduled Balance   (fka In Bankruptcy - scheduled balance)",
  "Prepaid loans - number",
  "Prepaid loans - principal",
  "Unscheduled Principal Collections/Other Principal Adjustments   (fka Total unscheduled principal)",
  "Total Penalty for the period",
  "Realized Loss (Gain) to Trust   (fka Current realized losses (gains))",
  "Aggregage Realized Loss on Loans   (fka Cumulative realized losses)",
  "Most Recent Net ASER Amount   (fka Appraisal Reduction Amount)",
  "Cumulative ASER Amount   (fka Cumulative Appraisal Reduction)",
  "Total P&I Advance Outstanding",
  "Total T&I Advance Outstanding",
  "Other Expense Advance Outstanding",
  "Reserve Balances",
  "LOC Balances",
  "Amortization WAM",
  "Maturity WAM",
  "Calculated WAC",
  "Matured Performing Loan - Number",
  "Matured Performing Loan - Ending Scheduled Balance   (fka Matured Performing Loan - Scheduled Balance)",
  "Matured Non-Performing - Number",
  "Matured Non-Performing Loan - Ending Scheduled Balance   (fka Matured Non-Performing - Scheduled Balance)"
 ],
 "LPER": [
  "Transaction ID",
  "Group ID",
  "Loan ID",
  "Prospectus Loan ID",
  "Distribution Date",
  "Current Beginning Scheduled Balance",
  "Current Ending Scheduled  Balance",
  "Paid Through Date",
  "Current Index Rate",
  "Current Note Rate",
  "Maturity Date",
  "Servicer and Trustee Fee Rate",
  "Fee Rate/Strip Rate 1",
  "Fee Rate/Strip Rate 2",
  "Fee Rate/Strip Rate 3",
  "Fee Rate/Strip Rate 4",
  "Fee Rate/Strip Rate 5",
  "Net Rate ",
  "Next Index Rate",
  "Next Note Rate",
  "Next Rate Adjustment Date",
  "Next Payment Adjustment Date",
  "Scheduled Interest Amount",
  "Scheduled Principal Amount",
  "Total Scheduled P&I Due",
  "Negative Amortization/Deferred Interest Capitalized Amount",
  "Unscheduled Principal Collections",
  "Other Principal Adjustments",
  "Liquidation/Prepayment Date",
  "Prepayment Premium/Yield Maintenance (YM) Received",
  "Prepayment Interest Excess (Shortfall)",
  "Liquidation/Prepayment Code",
  "Most Recent Net ASER Amount",
  "EMPTY FIELD   (fka Most Recent ASER Date)",
  "Cumulative ASER Amount",
  "Actual Balance",
  "Total P&I Advance Outstanding",
  "Total T&I Advance Outstanding",
  "Other Expense Advance Outstanding",
  "Payment Status of Loan   (fka Status of Loan)",
  "In Bankruptcy (Y/N)",
  "Foreclosure Start Date",
  "REO Date",
  "Bankruptcy Date",
  "Net Proceeds Received on Liquidation",
  "Liquidation Expense",
  "Realized Loss to Trust",
  "Date of Last Modification",
  "Modification Code",
  "Modified Note Rate",
  "Modified Payment Amount",
  "Preceding Fiscal Year Revenue",
  "Preceding Fiscal Year Operating Expenses",
  "Preceding Fiscal Year NOI",
  "Preceding Fiscal Year Debt Svc Amount",
  "Preceding Fiscal Year DSCR (NOI)",
  "Preceding Fiscal Year Physical Occupancy",
  "Preceding Fiscal Year Financial As Of Date",
  "Second Preceding Fiscal Year Revenue",
  "Second Preceding Fiscal Year Operating Expenses",
  "Second Preceding Fiscal Year NOI",
  "Second Preceding Fiscal Year Debt Service Amount",
  "Second Preceding Fiscal Year DSCR (NOI)",
  "Second Preceding Fiscal Year Physical Occupancy",
  "Second Preceding Fiscal Year Financial As Of Date",
  "Most Recent Revenue",
  "Most Recent Operating Expenses",
  "Most Recent NOI",
  "Most Recent Debt Service Amount",
  "Most Recent DSCR (NOI)",
  "Most Recent Physical Occupancy",
  "Most Recent Financial As of Start Date",
  "Most Recent Financial As of End Date",
  "Most Recent Valuation Date",
  "Most Recent Value",
  "Workout Strategy",
  "Most Recent Special Servicer Transfer Date",
  "Most Recent Master Servicer Return Date",
  "Date Asset Expected to Be Resolved or Foreclosed",
  "EMPTY FIELD   (fka Year Renovated)",
  "Current Hyper Amortizing Date ",
  "Most Recent Financial Indicator",
  "Last Setup Change Date",
  "Last Loan Contribution Date",
  "Last Property/Collateral Contribution Date",
  "Number of Properties",
  "Preceding Fiscal Year DSCR Indicator",
  "Second Preceding Fiscal Year DSCR Indicator",
  "Most Recent  DSCR Indicator",
  "NOI/NCF Indicator",
  "Date of Assumption",
  "Preceding Fiscal Year NCF",
  "Preceding Fiscal Year DSCR (NCF)",
  "Second Preceding Fiscal Year NCF",
  "Second Preceding Fiscal Year DSCR (NCF)",
  "Most Recent NCF",
  "Most Recent DSCR (NCF)",
  "Defeasance Status",
  "ARA (Appraisal Reduction Amount)",
  "ARA Date",
  "EMPTY FIELD   (fka Credit Tenant Lease)",
  "Other Interest Adjustment ",
  "Cumulative Accrued Unpaid Advance Interest",
  "Total Reserve Balance",
  "Date Added to Servicer Watchlist",
  "Special Servicing Fee Amount plus Adjustments",
  "Reimbursed Interest on Advances",
  "Workout Fee Amount",
  "Liquidation Fee Amount",
  "Non Recoverability Determined",
  "Closing Date of Original Document Permitted Extension",
  "Total Loan Amount at Origination",
  "Current Lockbox Status   (fka Empty Field)",
  "Liquidation Sales Price",
  "Amounts Due Servicers and Trustee",
  "Amounts Held Back for Future Payment",
  "Accrued Interest",
  "Additional Trust Fund Expense",
  "Current Period Adjustment to Loan - Principal",
  "Date of Current Period Adjustment to Loan",
  "Cumulative Adjustments to Loan",
  "Advanced by Trust / Non Recoverable Reimbursements to Servicer - Current Month",
  "Anticipated Amount to be Advanced by Trust - Left to Reimburse Servicer",
  "Other (Shortfalls)/Refunds (fka Other Shortfalls/Refunds)",
  "Deferred Interest - Cumulative     ",
  "Deferred Interest Collected     ",
  "Reason for SS Transfer",
  "Advanced by Trust - Cumulative",
  "Non Cash Principal Adjustment ",
  "Modification Execution Date",
  "Modification Booking Date",
  "Current Period Adjustment to Loan - Other",
  "Master Servicer",
  "Special Servicer",
  "Reporting Period Begin Date",
  "Reporting Period End Date",
  "Modification Indicator",
  "Asset Subject to Demand",
  "Status of Asset Subject to Demand",
  "Demand Resolution Date",
  "Repurchase or Replacement Reason",
  "Post Modification Amortization Period",
  "Current Non Recoverable Interest",
  "Cumulative Non Recoverable Interest",
  "Lead Transaction ID",
  "ARD Interest - Cumulative",
  "Anticipated Repayment Date (ARD) Interest Collected",
  "Advanced by Trust - Workout Delayed Reimbursement Amounts (WODRA) to Servicer - Current Month",
  "Disclosable Special Servicing Fees",
  "Repurchase Amount",
  "Excess Liquidation Proceeds",
  "Current ARM Index",
  "Index Rate Adjustment Factor"
 ],
 "PROP": [
  "Transaction ID",
  "Loan ID",
  "Prospectus Loan ID",
  "Property ID",
  "Distribution Date",
  "Cross-Collateralized Loan Grouping",
  "Property Name",
  "Property Address",
  "Property City",
  "Property State",
  "Property Zip Code",
  "Property County",
  "Property Type",
  "Year Built",
  "Year Last Renovated",
  "Current Net Rentable Square Feet   (fka Net Square Feet at Contribution)",
  "Current Number of Units/Beds/Rooms   (Number of Units/Beds/Rooms at Contribution)",
  "Property Status",
  "Allocated Percentage of Loan at Contribution",
  "Current Allocated Percentage",
  "Current Allocated Ending Scheduled Loan Amount",
  "Ground Lease (Y/N/S)",
  "EMPTY FIELD   (fka Other Escrow/Reserve Balances)",
  "Most Recent Valuation Date",
  "Most Recent Value",
  "Date Asset Expected to be Resolved or Foreclosed",
  "Foreclosure Start Date",
  "REO Date",
  "Most Recent Physical Occupancy",
  "Most Recent Occupancy As Of Date",
  "Date Lease Rollover Review",
  "Pct. Sq. Feet expiring 1-12 months",
  "Pct. Sq. Feet  expiring 13-24 months",
  "Pct. Sq. Feet expiring 25-36 months",
  "Pct. Sq. Feet  expiring 37-48 months",
  "Pct. Sq. Feet  expiring 49+ months",
  "Largest Tenant",
  "Square Feet of Largest Tenant",
  "Second Largest Tenant",
  "Square Feet of Second (2nd) Largest Tenant",
  "Third Largest Tenant",
  "Square Feet of Third (3rd) Largest Tenant",
  "Fiscal Year End Month",
  "Contribution Financials As Of Date",
  "Revenue at Contribution",
  "Operating Expenses at Contribution",
  "NOI at Contribution",
  "DSCR (NOI) at Contribution",
  "Valuation Amount at Contribution",
  "Valuation Date at Contribution",
  "Physical Occupancy at Contribution",
  "Date of Last Inspection",
  "Preceding Fiscal Year Financial As Of Date",
  "Preceding Fiscal Year Revenue",
  "Preceding Fiscal Year Operating Expenses",
  "Preceding Fiscal Year NOI",
  "Preceding Fiscal Year Debt Service Amount",
  "Preceding Fiscal Year DSCR (NOI)",
  "Preceding Fiscal Year Physical Occupancy",
  "Second Preceding Fiscal Year Financial As Of Date",
  "Second Preceding Fiscal Year Revenue",
  "Second Preceding Fiscal Year Operating Expenses",
  "Second Preceding Fiscal Year NOI",
  "Second Preceding Fiscal Year Debt Service Amount",
  "Second Preceding Fiscal Year DSCR (NOI)",
  "Second Preceding Fiscal Year Physical Occupancy",
  "Property Status Change Date",
  "Most Recent Revenue",
  "Most Recent Operating Expenses",
  "Most Recent NOI",
  "Most Recent Debt Service Amount",
  "Most Recent DSCR (NOI)",
  "Most Recent Financial As Of Start Date",
  "Most Recent Financial As Of End Date",
  "Most Recent Financial Indicator ",
  "NCF at Contribution",
  "DSCR (NCF) at Contribution",
  "Preceding Fiscal Year NCF",
  "Preceding Fiscal Year DSCR (NCF)",
  "Second Preceding Fiscal Year NCF",
  "Second Preceding Fiscal Year DSCR (NCF)",
  "Most Recent NCF",
  "Most Recent DSCR (NCF)",
  "NOI/NCF Indicator",
  "Deferred Maintenance Flag (Y/N)",
  "Date of Lease Expiration of Largest Tenant",
  "Date of Lease Expiration of Second (2nd) Largest Tenant",
  "Date of Lease Expiration of Third (3rd) Largest Tenant",
  "Property Condition",
  "Most Recent Valuation Source",
  "Credit Tenant Lease (Y/N)",
  "Fourth Largest Tenant ",
  "Square Feet of Fourth (4th) Largest Tenant ",
  "Fifth Largest Tenant",
  "Square Feet of Fifth (5th) Largest Tenant",
  "Date of Lease Expiration of Fourth (4th) Largest Tenant",
  "Date of Lease Expiration of Fifth (5th) Largest Tenant",
  "Net Operating Income Indicator at Contribution",
  "Valuation Source at Contribution"
 ],
 "FINF": [
  "Transaction ID",
  "Prospectus Loan ID",
  "Property ID",
  "Financial As Of Start Date",
  "Financial As Of End Date",
  "Financial Statement Indicator",
  "Financial Statement Source",
  "Financial Line Item Code",
  "Financial Line Item Amount"
 ]
}
